import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "./providers/QueryProvider";
import { Toaster } from "sonner";
import { Analytics } from "@vercel/analytics/next"
import { SpeedInsights } from '@vercel/speed-insights/next';
import { LoaderProvider } from '../components/Loader/LoaderContext';
import RouteChangeListener from '../components/Loader/RouteChangeListener';
import LoaderOverlay from '../components/Loader/LoaderOverlay';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <QueryProvider>
          <LoaderProvider>
            <RouteChangeListener />
            <LoaderOverlay />
            <Toaster richColors position="top-center" />
            {children}
            <Analytics />
            <SpeedInsights />
          </LoaderProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
